// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEA9yfuqOGSVUzdhRcq83cBMA1gCmCsfY',
    appId: '1:434596075479:web:58ca10f3fa597a82b65d92',
    messagingSenderId: '434596075479',
    projectId: 'pflti-dev',
    authDomain: 'pflti-dev.firebaseapp.com',
    storageBucket: 'pflti-dev.appspot.com',
    measurementId: 'G-DSHPF4MQYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhGFm4maaDuCVoREykgopteH38aSXG40U',
    appId: '1:434596075479:android:34309e11c723ce0bb65d92',
    messagingSenderId: '434596075479',
    projectId: 'pflti-dev',
    storageBucket: 'pflti-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAoeZD-yX9NAzny3_dJZzlf7OHnud8pkI',
    appId: '1:434596075479:ios:985a56cb311c9c31b65d92',
    messagingSenderId: '434596075479',
    projectId: 'pflti-dev',
    storageBucket: 'pflti-dev.appspot.com',
    androidClientId: '434596075479-31mfi6vp6oglp9fjbj2hm8sc2e7hrroq.apps.googleusercontent.com',
    iosClientId: '434596075479-j4gqoqrmce1iovkdppqbabp8pac8lf6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.pfltibit',
  );
}
